plctlab/PLCT-Weekly

2020-02-24.md

Update 2020-02-24, add MLIR articles summary

---

2020-03-02.md

Update the 2020-03-02 to add the content of OpenArkCompiler and LLVM/Clang for RISC-V.

Update the 2020-03-02

---

2020-04-27.md

add MLIR article

---

2020-07-16.md

添加第五期的RVV工作进展

---

2020-08-16.md

修正永恒天平的工作内容

---

2020-09-01.md

Add committed and reviewing patches.

Add MLIR to 20200901

---

2020-09-16.md

添加MLIR：committed patches * 2 + reviewing patch * 1
添加CIRCT：知乎文章 - CIRCT llhd-sim工具分析

Add MLIR and CIRCT to 20200916

---

2020-11-16.md

add other works of PLCT

---

2020-11-16.md

向20201116添加:
- 两个正在review的patch
- 一个知乎文章
- 一个B站视频

Add MLIR to 20201116

---

2020-12-01.md

向20201201添加两个已提交patch，一个正在review的patch.

Add MLIR to 20201201

---

2020-12-16.md

添加MLIR相关工作：
committed patch x 1
reviewing patch x 1
文章 x 2
视频 x 1

Add MLIR to 20201216

---

2021/2021-01-01.md

添加MLIR工作：
- Patch * 1
- 提交Bug * 1
- 知乎文章 * 1

Add MLIR to 20200101

---

2021/2021-01-01.md

add toolchain work with zfinx, and the link of project

add toolchain work with zfinx

---

2021/2021-01-16.md

MLIR开源工作：
- Patch x 1
近期进行调研工作，分配给MLIR的时间较少，还被抢了一个大Patch，心疼TT

Add MLIR to 20210116

---

2021/2021-02-01.md

- MLIR patch x 1
- AutoDiff report x 1

Add MLIR and AutoDiff to 20210201

---

2021/2021-03-01.md

Add PLCT GNU Toolchain process introduce.

Add PLCT GNU Toolchain process

---

2021/2021-03-01.md

- 知乎回答 x 1
- 知乎文章 x 1
- 知乎视频 x 1

Add MLIR to 20210301

---

2021/2021-04-01.md

- 教训分享 x 1
- 发起讨论 x 1
本月重点在做论文的工作～

Add MLIR to 20210401

---

2021/2021-05-01.md

Add PLCT works in GNU toolchain within last month.

Add PLCT works in GNU toolchain

---

2021/2021-05-01.md

Add MLIR to 20210501

---

2021/2021-06-01.md

add Liaoshihua's work in May

---

2021/2021-06-01.md

- 知乎文章 x 1
- buddy-mlir 进展 x 1

Add MLIR to 20210601

---

2021/2021-06-01.md

add rvv auto-vectorization status： commit https://reviews.llvm.org/D99509，https://reviews.llvm.org/D101469

add rvv auto-vectorization status

---

2021/2021-06-01.md

add rvv auto-vectorization test report

---

2021/2021-07-01.md

- buddy-mlir 进展 x 1
- 知乎文章 x 1

Add MLIR to 20210701

---

2021/2021-08-01.md

- buddy-mlir 同步上游代码
- 知乎文章 x 1
- Fix RVV doc patch x 1

Add MLIR to 20210801

---

2021/2021-09-01.md

- MLIR RVV Dialect RFC
- MLIR RVV Dialect Initial Patch (under review)
- RISC-V Mentorship: MLIR Convolution Vectorization

Add MLIR to 20210901

---

2021/2021-09-01.md

这边更新了一下Rust / Rust for RISC-V的进展

Rust / Rust for RISC-V的进展更新

---

2021/2021-09-01.md

update openEuler riscv project status

oE riscv update

---

2021/2021-10-01.md

Add the work status of the OpenJDK team.

Add the work status of the OpenJDK team

---

2021/2021-10-01.md

- Upstream RVV Dialect
- LFX - RVI Mentorship
- Buddy project

Add 20211001 to MLIR

---

2021/2021-11-01.md

- Upstream RVV Dialect Proposal.
- Upstream MLIR Built-in Scalable Vector Type Discussion.
- Buddy Project PRs and WIPs.

Add MLIR to 20211101

---

2021/2021-11-01.md

Update PLCT-GNU team's works in Oct.

Update PLCT-GNU team's works in Oct

---

2021/2021-12-01.md

openeuler riscv 2021.12

---

2021/2021-12-01.md

- Upstream MLIR RVV Dialect
- LFX-RVI Mentorship
- Buddy Project

Add MLIR to 20211201

---

2022/2022-01-01.md

- Upstream RVV Dialect
- LFX-RVI Mentorship
- Buddy Project

Add MLIR to 20220101

---

2022/2022-01-01.md

Update the current status and the progress of ETS

Update the progress of ETS

---

2022/2022-01-01.md

Update PLCT-GNU team works in 2021/12, welcome to 2022, happy new year!

Update PLCT-GNU team works in 2021/12

---

2022/2022-01-01.md

add oerv report

---

2022/2022-02-01.md

Signed-off-by: Chen Wang <wangchen20@iscas.ac.cn>

aosp update 2022/2

---

2022/2022-02-01.md

- Upstream RVV Dialect
- LFX - RVI Mentorship
- Buddy Project

Add MLIR to 20220201

---

2022/2022-02-01.md

add arch linux to 20220201

---

2022/2022-02-01.md

Update GNU team works in Jan

---

2022/2022-03-01.md

Update PLCT GNU team works within Feb 2022.

PLCT GNU team works

---

2022/2022-04-01.md

Add PLCT-GNU team works on March.

Update PLCT-GNU team works

---

2022/2022-04-01.md

Sorry for the late PR
/cc @ice1000

Update 2022-04-01 with Aya team works

---

2022/2022-04-01.md

- Upstream RVV Dialect Proposal
- LFX - RVI Mentorship
- Buddy Project

Add MLIR to 20220401.

---

2022/2022-05-01.md

Update PLCT-GNU team works in April.

PLCT-GNU team works in April

---

2022/2022-05-01.md

Signed-off-by: Ryan Qian <i@bitbili.net>

2022-05-01.md: update Gentoo

---

2022/2022-05-01.md

- Upstream RVV Dialect Proposal
- OSPP 2022 Mentorship

Add MLIR to 20220501.

---

2022/2022-06-01.md

AYA: Update 2022-06-01 with Aya team works

---

2022/2022-06-01.md

Update the team works of OpenJDK for 2022-06-01

Update the team works of OpenJDK for 2022-06-01

---

2022/2022-06-01.md

- Upstream MLIR
- OSPP Mentorship

Add MLIR to 20220601

---

2022/2022-07-01.md

Signed-off-by: Chen Wang <wangchen20@iscas.ac.cn>

aosp for riscv status update 2022/7

---

2022/2022-07-01.md

- Upstream MLIR RVV Proposal
- OSPP 2022

Add MLIR to 20220701

---

2022/2022-07-01.md

Update GNU team works in 2022 Jun, try hard in the rest of this year!

Update GNU team works in 2022 Jun

---

2022/2022-08-01.md

Signed-off-by: Chen Wang <wangchen20@iscas.ac.cn>

aosp status update for 2022/8

---

2022/2022-08-01.md

Update GNU team works in July, about patches and slides.

Update GNU team works in July

---

2022/2022-08-01.md

- Upstream MLIR + RVV
- OSPP 2022

Add MLIR to 20220801

---

2022/2022-08-01.md

AYA: update aya-prover (2022-08-01)

---

2022/2022-08-01.md

Update 2022-08-01.md for CAAT

---

2022/2022-09-01.md

Update for OpenJDK8 backporting

Update for OpenJDK8 backporting

---

2022/2022-09-01.md

some llvm and gollvm

---

2022/2022-09-01.md

- Upstream RVV Dialect Proposal
- OSPP Mentorship

Add MLIR to 20220901.

---

2022/2022-09-01.md

Update GNU team's works in August, try harder in Sep.

Update GNU team works in August

---

2022/2022-09-01.en.md

This pull request adds English translation for the September report. Minor changes to typesetting and punctuation are also made for better readability in English.

2022: add English translation for the September report

---

2022/2022-10-01.md

Update GNU team works in Sep, divided into four part.

Update GNU team works in Sep

---

2022/2022-10-01.md

- Upstream RVV Dialect Proposal
- OSPP Mentorship

Add MLIR to 20221001

---

2022/2022-10-01.en.md
2022/2022-10-01.md

This pull request contains my English translation for the October monthly report. It also contains a fix for YouTube links/timestamps for the GNU Tools Cauldron recordings.
Review and suggestions welcome.

[READY] 2022-10-01: English Translation and Minor Fix for GNU Tools Cauldron Links

---

2022/2022-11-01.md

Update 2022-11-01.md for rvlab

Update 2022-11-01.md for rvlab

---

2022/2022-11-01.md

- Upstream MLIR + RVV.
- OSPP Projects.
- Buddy Compiler.

Add MLIR to 20221101.

---

2022/2022-11-01.md

Update GNU team works in Nov, about patches progress, issues and slides.

Update GNU team works in Nov.

---

2022/2022-11-01.en.md

This pull request introduced en_US translation for the November issue.

2022/2022-11-01: add en_US translation

---

2022/2022-12-01.md

Signed-off-by: Chen Wang <wangchen20@iscas.ac.cn>

aosp monthly update 2022/11

---

2022/2022-12-01.md

llvm and gollvm

---

2022/2022-12-01.md

Update for backporting of OpenJDK8

Update for backporting of OpenJDK8

---

2022/2022-12-01.md

- MLIR Upstream Commits.
- Buddy Compiler New Features.

Add MLIR to 20221201.

---

2023/2023-01-01.md

Update OpenJDK8 in 2023-01-01.md

Update OpenJDK8 in 2023-01-01.md

---

2023/2023-01-01.md

Update GNU team's works in Dec, about patches, issues recordings and meetings.
Happy New Year!

Update GNU team's works in Dec

---

2023/2023-01-01.md

Add MLIR to 20230101.

---

2023/2023-01-01.en.md

This pull request introduces an English translation for our January report.

2023/2023-01-01.en.md: add English translation

---

2023/2023-02-01.md

Update Archlinux for 2023-02-01

---

2023/2023-02-01.md

Update OpenJDK8 for 2023-02-01

Update OpenJDK8 for 2023-02-01

---

2023/2023-02-01.md

Add MLIR to 20230201.

---

PLCT-Roadmap-2023.md

一些相关信息，以及使用场景：https://github.com/systemd/systemd/pull/26097

新增对 LLVM MC RISC-V PE/COFF 支持的许愿

---

2023/2023-03-01.md

Update GNU team works in Feb 2023.

Update GNU team works.

---

2023/2023-04-01.md

Update for OpenJDK8 2023-04-01

Update for OpenJDK8 2023-04-01

---

2023/2023-04-01.md

Update GNU team work in March, about the extension implyment and bug fixes, keep going harder .

Update GNU team works in March

---

2023/2023-03-01.md

- Clean up title hierarchy and revised section titles to better adhere to Chinese language habits (for future reference).
- Review and revise sentences, expressions, and proses.
- Fix several broken links.
- Lint Markdown syntaxes.

2023-03-01.md: lint formatting and proses

---

2023/2023-04-01.md

2023-04-01: 修缮排版、格式和文法问题

---

2023/2023-05-01.md

本 PR 修缮模板框架中的排版、格式和文法问题，@lazyparser 请考虑在后续月报中套用本次修改。

2023-05: 修缮模板框架中的排版、格式和文法问题

---

2023/2023-04-01.md

2023-04-01: 小范围格式修缮

---

2023/2023-05-01.md

Update  for OpenJDK8 2023-05-01

Update  for OpenJDK8 2023-05-01

---

2023/2023-04-01.en.md

This pull request adds English translation for the April report.

2023-04-01: add English translation

---

2023/2023-05-01.md

Update GNU team work in April, Happy Labor Day :)

Update GNU team work in April

---

2023/2023-06-01.md

Signoff: Cheng Li <shiptux@gmail.com>

Update DynamoRIO by shiptux

---

2023/2023-06-01.md

Add Aya 5 月

---

2023/2023-05-01.md

2023-05-01: 修缮格式和文法问题

---

PLCT-Roadmap-2023.md

本 PR 主要修缮一些词汇拼写和排版问题，以及某些地方存在的中英混杂问题。

PLCT-Roadmap-2023.md: minor typesetting fixes

---

2023/2023-07-01.md

Update GNU team's work in June.

Update GNU team's work in June.

---

2023/2023-07-01.md

2023-07-01: update luajit progress

---

2023/2023-07-01.md

本 PR 修缮一些七月月报中存在的排版、格式和文法问题，确保渲染效果无误等

2023-07-01: 修缮排版、格式和文法

---

2023/2023-08-01.md

Update GNU teams work in July, work harder.

Update GNU teams work in July

---

2023/2023-09-01.md

Update GNU team work in August.

Update GNU team work in Aug

---

README.md

It's been quite a while without updates.

Remove zhihu subscription instructions

---

2023/2023-10-01.md

Sorry for the late submission, I forgot about this.

Update box64 and DynamoRIO

---

2023/2023-11-01.md

Update GNU team works in Oct, try harder in Nov.

Update GNU team works in Oct

---

2023/2023-11-01.md

IDE逐步实现的计划为：
1. [WIP] 对标Eclipse IDE for Embedded C/C++ Developers，集合其覆盖的各类插件的源码，初步形成RuyiSDK IDE的初始源码版本。要求是集成的源码打包后能够产出功能等同于Eclipse IDE for Embedded C/C++ Developers的IDE安装程序。
2. [todo] 界面定制。
3. [todo] 实现IDE 包管理器。要求是能够下载包管理器定义的各类交叉编译工具链，以及目标环境操作系统sysroot。并支持查看下载状态和卸载已下载的资源。
4. [todo] 在新建C Project 、C/C++ Project中，增加2款指定的目标RISC-V硬件开发板选项。
5. [todo] 实现 RuyiSDK 配置工具，提供对交叉编译器选项的配置。
(2-5没有严格的开发顺序要求)

add RuyiSDK IDE works

---

2023/2023-12-01.md

Update 2023-12-01.md with contributions made within Nov. 2023

---

2023/2023-12-01.md

Update GNU team work in Nov

---

2024/2024-01-01.md

Update GNU team work in Dec, happy new year.

Update GNU team work in Dec

---

2024/2024-01-01.md

Add Aya for 2023-12

---

2024/2024-01-01.md

Add MLIR to 20240101.

---

2024/2024-01-01.md

Update 2024-01-01 with contributions in ruyisdk/llvm-project

---

2024/2024-02-01.md

[ruyisdk/llvm-project] Update 2024-02-01.md

---

2024/2024-02-01.md

Update OpenJDK8 in 2024.02.01

---

2024/2024-03-01.md

Update OpenJDK RV64/RV32 for zifeihan in 20240301

Update OpenJDK RV64/RV32 for zifeihan in 20240301

---

2024/2024-03-01.md

Update GNU team work in Feb 2024.

Update GNU team work

---

2024/2024-03-01.md

Update ruyisdk/llvm-project to 2024-03-01.md

---

2024/2024-04-01.md

Update ruyisdk/llvm-project to 2024-04-01.md

---

2024/2024-04-01.md

Update GNU team's work in March.

Update GNU team's work in March

---

2024/2024-04-01.md

2024/2024-04-01.md: add ruyipkg

---

2024/2024-05-01.md

add ruyisdk/llvm-project to 2024-05-01

---

2024/2024-05-01.md

Update OpenJDK RV64/RV32 for zifeihan in 20240501

Update OpenJDK RV64/RV32 for zifeihan in 20240501

---

2024/2024-06-01.md

add ruyisdk/llvm-project to 2024-06-01

---

2024/2024-06-01.md

Update OpenJDK RV64/RV32 for zifeihan in 20240601

Update OpenJDK RV64/RV32 for zifeihan in 20240601

---

2024/2024-07-01.md

add ruyisdk/llvm-project to 2024-07-01

---

2024/2024-08-01.md

add ruyisdk/llvm-project to 2024-08-01

---

2024/2024-08-01.md

Update GNU team work in July

---

2024/2024-10-01.md

In this month,  our 8 team members had 53 contributions in total, including 49 commits or PRs, 2 community articles and 2 community activities.
[Rendered](https://github.com/luojia65/PLCT-Weekly/blob/b8fd9979ac094daf031db87e340bb3c465a4445c/2024/2024-10-01.md#rustsbi-%E5%B0%8F%E9%98%9F)

Update RustSBI Team section in 2024-10-01.md

---

2024/2024-10-01.md

Update GNU team work in Sep，welcome new intern CYY.

Update GNU team work in Sep

---

2024/2024-10-01.md

Update 2024-10-01.md for TPU/J123

---

2024/2024-11-01.md

Update GNU team work.

---

2024/2024-11-01.md

Update 2024-11-01.md for Aya

---

2024/2024-12-01.md

updata j123

---

2024/2024-12-01.md

Update 2024-12-01.md for Aya

---

2025/2025-01-01.md

update 2025-01 J123

---

2025/2025-01-01.md

Update GNU team work in Dec.

---

2025/2025-01-01.md

2025-01-01: add ruyipkg

---

2025/2025-01-01.md

任务：移植部分yast-installation前置依赖包到Eulaceura

2025-01-01: transplant dependencies required by yast-Installation for Eulaceura

---

2025/2025-02-01.md

2025-02-01: ruyipkg

---

2025/2025-02-01.md

Update GNU team work in Jan, happy Spring Festival!

Update GNU team work in Jan

---

2025/2025-03-01.md

2025-03-01: Update CIRCT task.

---

2025/2025-05-01.md
2025/2025-06-01.md

- Go
- FreeBSD src
- FreeBSD pkgs
- QEMU

Update Apr/May contribution by Meng Zhuo

---

2025/2025-05-01.md
2025/2025-06-01.md

Add GNU submission records for April.

Add GNU submission records for April and May.

---

2025/plct-monthly-0071.md

上个月的产出都不是外部可见的，所以没发周报，现在有做出来的特性了。我有空会录一些 gif 放到 readme 里面

Add Aya progress

---

2025/plct-monthly-0072.md

Update GCC part

---

2025/plct-monthly-0073.md

Update plct-monthly-0073.md GCC part.

---

2025/plct-monthly-0073.md

Added new section for eunomia-bpf with various links and updates.

Add eunomia-bpf section with recent updates
